FROM node:lts-slim

# Set the working directory in the container
WORKDIR /usr/src/app

#FROM base AS all-deps
#RUN bun install

# Install git and other package dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

RUN git clone https://github.com/jkrumm/free-planning-poker.git

WORKDIR /usr/src/app/free-planning-poker/fpp-server

RUN npm i -g bun
RUN bun install
ENV NODE_ENV=production
CMD ["bun", "run", "src/index.ts"]
#CMD ["bun", "run", "buildit"]
#CMD ["bun", "run", "start"]
EXPOSE 3003
#
#WORKDIR /usr/src/app/free-planning-poker/fpp-server
#
#RUN bun install
#
#ENV NODE_ENV=production
#
#CMD ["bun", "run", "start"]
#
#EXPOSE 3003