apiVersion: 1

datasources:
  - name: MariaDB
    type: mysql
    url: mariadb:3306
    user: read
    jsonData:
      maxOpenConns: 7
      maxIdleConns: 3
      maxIdleConnsAuto: true
      connMaxLifetime: 7200
    secureJsonData:
      password: ${DB_READ_PW}

  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: jkrumm
      defaultBucket: monitoring
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUX_TOKEN}

  - name: InfluxDB_v2_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: InfluxQL
      dbName: monitoring
      httpHeaderName1: "Authorization"
    secureJsonData:
      httpHeaderValue1: 'Token ${INFLUX_TOKEN}'